### PR TITLE
feat(datasets): deny v1 routes and gql mutations if readonly

### LINKED ISSUE #3286: [demo] block all mutations when the read-only flag is set
For the demo instance to work, we must block all mutation graphql queries.

### PR DESCRIPTION
**Pull request by RogerHYang**
resolves #3286

### CODE REVIEW

**Review by anticorrelator — COMMENTED** [review]
hey roger, I can't tell which rest routes are denied if the readonly flag is set? is there something I need to do to set this for each route?

**Comment by RogerHYang** [comment]
> hey roger, I can't tell which rest routes are denied if the readonly flag is set? is there something I need to do to set this for each route?

all of them are being denied by the decorator

**Comment by anticorrelator** [comment]
> > hey roger, I can't tell which rest routes are denied if the readonly flag is set? is there something I need to do to set this for each route?
> 
> all of them are being denied by the decorator

do we want to allow the query and read routes? or are you thinking to just deny all of them

**Comment by RogerHYang** [comment]
> do we want to allow the query and read routes? or are you thinking to just deny all of them

i'm denying all of them to conserve CPU and DB usage

**Comment by anticorrelator** [comment]
ok, makes sense

**Review by anticorrelator — APPROVED** [review]

**Pull request merged**
