### PR TITLE
feat: added SQLEvaluator

### PR DESCRIPTION
**Pull request by ShashankVSG**
Added SQLEvaluator in the evaluators package that can be used to evaluate the SQL and the corresponding response generated by the LLM.

### CODE REVIEW

**Comment by ShashankVSG** [comment]
recheck

**Comment by ShashankVSG** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by axiomofjoy — APPROVED** [review]

**Comment by axiomofjoy** [comment]
CI is not passing, but the issue appears to be on `main`

**Comment by axiomofjoy** [comment]
Thanks for your contribution @ShashankVSG. `SQLEvaluator` is available in `arize-phoenix 4.5.0`.

**Pull request merged**
