### PR TITLE
feat(persistence): sql persistence

### PR DESCRIPTION
**Pull request by mikeldking**
Feature branch for #1689

### CODE REVIEW

**Review by RogerHYang — APPROVED** [review]

**Comment by Townsheriff** [comment]
Hi,

I've tried to setup this PR as it is now. Using sqlite and postgresql and could not get pass `sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here`. 

Is there some way I could attach a persistent store to the tool? Doesn't matter what it is. I'm looking it to run for deployed workload and look at traces afterwards.

**Comment by mikeldking** [comment]
> Hi,
> 
> 
> 
> I've tried to setup this PR as it is now. Using sqlite and postgresql and could not get pass `sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here`. 
> 
> 
> 
> Is there some way I could attach a persistent store to the tool? Doesn't matter what it is. I'm looking it to run for deployed workload and look at traces afterwards.

Hi @Townsheriff this is a feature branch so I can't really guarantee everything working as expected. However you will need greenlit for mac so you need SQLAlchemy[asyncio] . If you really need persistence Arize the SAAS platform also has a free tier. Hope that helps!

**Review by anticorrelator — APPROVED** [review]
ONE CEREMONIAL APPROVAL

kid

**Review by axiomofjoy — APPROVED** [review]
epic 🚀

**Pull request merged**
