### PR TITLE
docs: Typo Fix

### PR DESCRIPTION
**Pull request by RahulK4102**
Corrected "Costomizable" to "Customizable" in [README.md].

This pull request addresses a minor typo found in repository. The typo has been corrected to improve clarity and maintain the quality of the documentation.

This change is purely cosmetic and does not affect functionality.

### CODE REVIEW

**Comment by axiomofjoy** [comment]
Thanks @RahulK4102!

Please go ahead and sign the CLA and we'll merge this in!

**Review by axiomofjoy — APPROVED** [review]

**Comment by RahulK4102** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by RahulK4102** [comment]
@axiomofjoy I have read the CLA Document and I hereby sign the CLA

**Comment by axiomofjoy** [comment]
Thanks @RahulK4102 !

**Pull request merged**
