### PR TITLE
docs(quickstart): convert Phoenix inferences instructions to notebook

### PR DESCRIPTION
**Pull request by brainwavecoder9**
PR is not related to an existing open issue. 

Realized when following the [inferences quickstart](https://docs.arize.com/phoenix/inferences/phoenix-inferences) that an example notebook did not exist but the instructions at would be easy to convert. Note that the related change for PR #4592 is also reflected in this notebook.

This contribution was inspired by a public workshop hosted by the Brain Wave Collective (@brainwavecollective).

### CODE REVIEW

**Comment by brainwavecoder9** [comment]
recheck

**Comment by RogerHYang** [comment]
@brainwavecoder9 This should push to main instead. Can you please rebase? Thank you

**Comment by brainwavecoder9** [comment]
@RogerHYang I've rebased from main and I think you're good to go now

**Comment by mikeldking** [comment]
thanks @brainwavecoder9 !

**Pull request merged**
