### PR TITLE
feat: update bedrock.py to use messages API for claude

### PR DESCRIPTION
**Pull request by jlonge4**
Evals using new claude 3 are failing due to messages API not being supported. Copied format for claude function from anthropic.py

### CODE REVIEW

**Comment by jlonge4** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jlonge4** [comment]
@mikeldking

**Review by anticorrelator — COMMENTED** [review]
Thanks for the contribution! Have you tested whether or not the new messages API is backwards compatible for all Anthropic models? If not we'll probably want to use the old completion API for non Claude-3 models.

**Comment by jlonge4** [comment]
@anticorrelator of course! I checked this table first and saw that they are compatible all the way back! Source: https://docs.anthropic.com/claude/docs/models-overview

**Review by anticorrelator — CHANGES_REQUESTED** [review]
Thank you so much for the contribution @jlonge4! This is super helpful.

Before merging we'll need to also modify the `_create_request_body` and `_parse_output` methods

The input payload needs to be modified a bit:

```python
def _create_request_body(self, prompt: str) -> Dict[str, Any]:
    ...
    elif self.model_id.startswith("anthropic"):
        return {
            **{
                "anthropic_version": "bedrock-2023-05-31",
                "messages": self._format_prompt_for_claude(prompt),
                "temperature": self.temperature,
                "top_p": self.top_p,
                "top_k": self.top_k,
                "max_tokens": self.max_tokens,
                "stop_sequences": self.stop_sequences,
            },
            **self.extra_parameters,
        }
```

Also, the output of the new `messages` API has changed, so we'll need to change the `anthropic` section of `_parse_output`:

```python
def _parse_output(self, response: Any) -> Any:
    ...
    elif self.model_id.startswith("anthropic"):
        body = json.loads(response.get("body").read().decode())
        return body.get("content")[0]["text"]
```

I think once those are in we're good to go!

**Comment by jlonge4** [comment]
@anticorrelator thanks for those finishing touches, I should've caught that 😅

**Review by anticorrelator — APPROVED** [review]
This looks great! Thanks again @jlonge4

**Pull request merged**
