### PR TITLE
fix: handle None values in the context

### LINKED ISSUE #4300: [BUG] Issue in get_qa_with_reference function in Phoenix eval
**Describe the bug**
[get_qa_with_reference](https://github.com/Arize-ai/phoenix/blob/a3ff0f6b1c90f126db1249e877d2369ab9bffe02/src/phoenix/trace/dsl/helpers.py#L71C5-L71C26) function gives the below error in case no context is retrieved.

```TypeError: sequence item 0: expected str instance, NoneType found``` 

The error is at [this](https://github.com/Arize-ai/phoenix/blob/a3ff0f6b1c90f126db1249e877d2369ab9bffe02/src/phoenix/trace/dsl/helpers.py#L115) point. In the below screenshot, I have `None` in the reference column as no context was retrieved. 

Screenshot 2024-08-21 at 2 46 31 PM

**To Reproduce**
The error can reproduced by submitting a query that will not retrieve any context. 

**Expected behavior**
`None` values in the context should be properly handled.

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - Notebook Runtime [e.g. Jupyter]
 - Browser [e.g. chrome]
 - Arize Phoenix  4.25.0
 - Arize Phoenix Evals 0.15.0

### PR DESCRIPTION
**Pull request by bhardwaj-vipul**
Filter context with None values.

fixes #4300

### CODE REVIEW

**Comment by bhardwaj-vipul** [comment]
----------------------------------------------------------

I have read the CLA Document and I hereby sign the CLA

----------------------------------------------------------

**Comment by bhardwaj-vipul** [comment]
recheck

**Comment by RogerHYang** [comment]
maybe try again with just a single line of text without the dividers
```
I have read the CLA Document and I hereby sign the CLA
```

**Comment by bhardwaj-vipul** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by RogerHYang — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
