### PR TITLE
docs(evals): Cleaned up notebooks, adding GPT-3 to each one

### PR DESCRIPTION
**Pull request by jlopatec**
adding descriptions to each one around the template, making them have a common look and feel

### CODE REVIEW

**Comment by jlopatec** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jlopatec** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jlopatec** [comment]
I need to make one more fix to summarization, fixing the dataset download, one more quick update.

**Comment by jlopatec** [comment]
Checked in dataset fixes, so datasets are pulled from right place. Should be good to go.

**Comment by axiomofjoy** [comment]
@jlopatec Do you need help getting this PR to pass the pipeline?

**Comment by mikeldking** [comment]
@jlopatec as Xander points out, we have strong formatting rules for git diff purposes. For these notebooks I can see some motivation to keep the confusion matrix outputs but I think for now I'm going to sanitize them. Let us know via a ticket. 

Thanks for the pr.

**Pull request merged**
