### PR TITLE
docs: add getpass

### PR DESCRIPTION
**Pull request by duncankmckinnon**
Adding `getpass` package usage in tutorial notebooks per #1103.  Follows conventions and makes use of `getpass` wherever user specific input is needed to run the notebook, including api key, environment, account url, and index name.

### CODE REVIEW

**Review by duncankmckinnon — COMMENTED** [review]
recheck

**Comment by duncankmckinnon** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by duncankmckinnon** [comment]
recheck

**Review by axiomofjoy — APPROVED** [review]

**Comment by axiomofjoy** [comment]
Thanks for your contribution @duncankmckinnon!

**Comment by axiomofjoy** [comment]
You'll need to update the title of your PR to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to pass CI. A reasonable choice for this PR might be `docs: ...` or `chore: ...`

**Comment by mikeldking** [comment]
Welcome to the team @duncankmckinnon! Thanks for this.

**Pull request merged**
