### PR TITLE
feat: Support mistral

### PR DESCRIPTION
**Pull request by jlonge4**
Quick addition to Bedrock Model to support mistral flavors

### CODE REVIEW

**Review by RogerHYang — COMMENTED** [review]
Thanks for the PR! Small typo on line 181.

**Comment by jlonge4** [comment]
@RogerHYang my bad haha! Will edit asap

**Comment by RogerHYang** [comment]
@jlonge4 The PR is failing CI right now. The format may be slightly off. Can you please run the following command in the phoenix root directory? It should fix it for you. (You may need to `pip install tox` first.)

```console
% tox run -e ruff-mypy-test-phoenix_evals
```

**Comment by jlonge4** [comment]
@RogerHYang I just did a ruff check and got it sorted!

**Review by RogerHYang — APPROVED** [review]

**Comment by RogerHYang** [comment]
Thank you for your contribution!

**Pull request merged**
